#!/usr/bin/env bash

# set up files.

# difference in > and >> 
cat /autograder/submission/dummy.scm /autograder/source/tests.scm > /autograder/source/dummy.scm
cd /autograder/source

# run new_file.txt handling output and putting it in /autograder/results/results.json
# by default, output will (should) go to /autograder/results/stdout

npm run cli dummy.scm

# Copying stdout to results.json for autograder to read
cp /autograder/results/stdout /autograder/results/results.json